### ISSUE TITLE
[BUG]Cannot start Dungeon Mode

### ISSUE THREAD

**Issue by EcandoLoS** [elizeuangelo/fvtt-module-restrict-movement#1]
Clicking Dungeon Mode will result in this error.
![image](https://user-images.githubusercontent.com/71748621/213883797-1abbff63-b142-4a61-8d66-eb5dbda1d245.png)
Core:Foundry 10.291
System:DND5e 2.1.2

**Comment by elizeuangelo** [comment]
Have you tried pressing f5 and refreshing the page?
The module uses a document to store the information but Foundry sometimes behave oddly due to concurrency when updating documents. It could happen the document got broken, but there is a workflow on initialization precisely for that.

**Comment by EcandoLoS** [comment]
I have tried refreshing the page but the same problem still occur, and i find that two errors when I refresh the page.
Maybe it can explain why I cannot start the dungeon mode?
![image](https://user-images.githubusercontent.com/71748621/214076471-4a7a4909-c450-4f86-8c55-9578e4eb191f.png)
![image](https://user-images.githubusercontent.com/71748621/214076929-1262740a-28d2-4578-aef5-4b06a52a2984.png)

**Comment by elizeuangelo** [comment]
Try updating to v1.02 and test if the error persists.

**Comment by EcandoLoS** [comment]
Thanks! It works now.
